fail_fast: false
repos:
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -    id: black
         stages: [commit]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: flake8
        stages: [commit]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.1.0
    hooks:
    -   id: reorder-python-imports
-   repo: git://github.com/chewse/pre-commit-mirrors-pydocstyle
    rev: v2.1.1
    hooks:
    -   id: pydocstyle
        stages: [commit]
